### ISSUE TITLE
Identifier "strptime" is undefined

### ISSUE THREAD

**Issue by Noschvie** [FKW9/esp-smartmeter-netznoe#3]
What is missing to get "identifier "strptime" is undefined" solved ?

https://github.com/mitsubishievo99/esp-smartmeter-netznoe/blob/32dca8013baaa83d104a01f038344f367fa77a73/src/main.cpp#L140

**Comment by FKW9** [comment]
Since you already compiled the code successfully (#2), i am assuming its an IDE/linting problem.
strptime should be included with Arduino.h.
You can try including <time.h> or <TimeLib.h> though

**Comment by Noschvie** [comment]
strptime() can be found in .platformio\packages\framework-arduinoespressif32\tools\sdk\include\newlib\time.h
but this script isn't included.

Project can be compiled successfully, but it's strange... and the firmware crashed during boot.

**Comment by FKW9** [comment]
The answer to the problem is found [here](https://community.platformio.org/t/identifier-is-undefined-setenv-tzset/16162).
You can fix it by putting the following code after your includes.
`char *_EXFUN(strptime, (const char *__restrict, const char *__restrict, struct tm *__restrict));`
**This only works for ESP32!**
